urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework_swagger.views import get_swagger_view

from apps.home.views import IndexView
from apps.cv.views import GenerateCV, CvStaffIndex
from apps.core.views import DepartmentsIndex, GroupsIndex
from apps.edudep.views import (StudentsIndex, StudentDetailViewSet,
                               UchPlanGroupIndex, UchPlanStudentIndex,
                               UchPlanGroupDetailView, StudentCreateViewSet)
from apps.indplans.views import EducationalWork
from apps.abiturient.views import AbiturientsIndex, AbiturientView, AbiturientsIndexList
from apps.reports.views import StudentSpravkaView, StudentsMovementsJournalView
from apps.reports.views import (StudentsListInGroupView, UchPlanGroupCurrentDetailPDFView,
                                UchPlanStudentsBegunok, UchPlanStudentsCurrSemestr,
                                UchPlanStudentsSemestr, UchPlanGroupDetailPDFView,
                                StudentCardView, JournalOfMarks, StudentByDepartments,
                                StudentByNationality)


admin.site.site_header = 'BDOC Web'
schema_view = get_swagger_view(title='BDOC API')

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^docs/api/', schema_view),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('apps.core.urls', namespace='core')),
    url(r'^auth/', include('apps.auth.urls', namespace='auth')),
    url(r'^cv/staff/$', CvStaffIndex.as_view(), name='cv_list'),
    url(r'^cv/staff/(?P<pk>\d+)/$', GenerateCV.as_view(), name='cv_id'),
    url(r'^departments/$', DepartmentsIndex.as_view(), name='departments_list'),
    url(r'^groups/$', GroupsIndex.as_view(), name='groups_list'),
    url(r'^students/$', StudentsIndex.as_view(), name='students_list'),
    url(r'^uchplans/groups/$', UchPlanGroupIndex.as_view(), name='uchplgroup_list'),
    url(r'^uchplans/groups/(?P<pk>\d+)/$', UchPlanGroupDetailView.as_view(), name='uchplgroup_detail'),
    url(r'^uchplans/students/$', UchPlanStudentIndex.as_view(), name='uchplstudent_list'),
    url(r'^uchplans/students/(?P<pk>\d+)/b/print/$', UchPlanStudentsBegunok.as_view(), name='uchplstudent_begunok'),
    url(r'^indplan/eduwork/$', EducationalWork.as_view(), name='eduwork_list'),
    url(r'^indplan/eduwork/(?P<pk>\d+)/$', EducationalWork.as_view(), name='eduwork_id'),
    url(r'^abitur/inner$', AbiturientsIndex.as_view(), name='abitur_inner_list'),
    url(r'^abitur/$', AbiturientsIndexList.as_view(), name='abitur_list'),
    url(r'^abitur/inner/(?P<pk>\d+)/$', AbiturientView.as_view(), name='abitur_inner_id'),
    url(r'^reports/student/(?P<pk>\d+)/spravka/$', StudentSpravkaView.as_view(), name='student_spravka'),
    url(r'^reports/group/(?P<pk>\d+)/journal_students/$', StudentsMovementsJournalView.as_view(), name='students_movements'),
    url(r'^reports/group/(?P<pk>\d+)/studentsingr/$', StudentsListInGroupView.as_view(), name='students_movements'),
    url(r'^reports/group/(?P<pk>\d+)/current_v/print/$', UchPlanGroupCurrentDetailPDFView.as_view(), name='current_vedomost_print'),
    url(r'^reports/group/(?P<pk>\d+)/v/print/$', UchPlanGroupDetailPDFView.as_view(), name='vedomost_print'),
    url(r'^reports/group/(?P<pk>\d+)/journal/download/$', JournalOfMarks.as_view(), name='journal_download'),
    url(r'^reports/student/(?P<pk>\d+)/curr_uchplan/$', UchPlanStudentsCurrSemestr.as_view(), name='curruchplan_print'),
    url(r'^reports/student/(?P<pk>\d+)/curr_uchplan/(?P<sem>\d+)/$', UchPlanStudentsSemestr.as_view(), name='semuchplan_print'),
    url(r'^reports/student/(?P<pk>\d+)/studentcard/$', StudentCardView.as_view(), name='student_card_print'),
    url(r'^reports/bydepartment/$', StudentByDepartments.as_view(), name='student_by_department'),
    url(r'^reports/bynationality/$', StudentByNationality.as_view(), name='student_by_nationality'),
    url(r'^student/new/$', StudentCreateViewSet.as_view(), name='student_create'),
    url(r'^student/(?P<pk>\d+)/$', StudentDetailViewSet.as_view(), name='student_detail'),
    url(r'^api/docs/', include('rest_framework_docs.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/edudep/models.py
from django.utils import timezone
from django.db import models
from apps.core.models import Groups
from apps.hr.models import Staff
from .managers import UchPlManager
import apps.edudep.utils as marks_class
from apps.core.models import MarksSettings as marks_settings

# Catalogue imports
from apps.catalogue.models import Nationality, Enrollment, SEX_CHOISES, FEMALE
from apps.catalogue.models import LearningStatus, LearningForm, Country
from apps.catalogue.models import Region, District, City, Subject
from apps.catalogue.models import CONTROL_TYPE, EXAM, MARKS_CHOISES, NOT_DEFINED, MARITIAL_STATUS, SINGLE

from django.utils.translation import ugettext_lazy as _


# Student Information.
class Student(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name=_('id'), auto_created=False)
    first_name = models.CharField(max_length=100, verbose_name=_('first_name'), null=False)
    name = models.CharField(max_length=100, verbose_name=_('name'), null=False)
    last_name = models.CharField(verbose_name=_('last_name'), max_length=100)
    birthday = models.DateField(null=False, verbose_name=_('birthday'), default="1980-01-01")
    sex = models.IntegerField(choices=SEX_CHOISES, default=FEMALE, verbose_name=_('sex'))
    maritial_status = models.IntegerField(choices=MARITIAL_STATUS, default=SINGLE, verbose_name=_('maritial_status'))
    nationality = models.ForeignKey(Nationality, on_delete=models.DO_NOTHING, verbose_name=_('nationality'), default=0)
    citizenship = models.ForeignKey(Country, on_delete=models.DO_NOTHING, verbose_name=_('citizenship'), default=0)
    phone = models.CharField(verbose_name=_('phone'), max_length=18)
    email = models.CharField(verbose_name=_('email'), max_length=100)
    enrollment = models.ForeignKey(Enrollment, on_delete=models.DO_NOTHING, verbose_name=_('enrollment'), default=0)
    learning_status = models.ForeignKey(LearningStatus, on_delete=models.DO_NOTHING, verbose_name=_('learning_status'), default=0)
    learning_form = models.ForeignKey(LearningForm, verbose_name=_('learning_form'), default=0)
    profile_img = models.CharField(max_length=100, verbose_name=_('profile_img'), default='images/staff/profile.png')
    group_code = models.ForeignKey(Groups, verbose_name=_('group_code'), default=0)
    course = models.PositiveIntegerField(verbose_name=_('course'), default=1)
    semestr = models.PositiveIntegerField(verbose_name=_('semestr'), default=1)
    contract_summ = models.PositiveIntegerField(verbose_name=_('contract_summ'), default=0)
    created_at = models.DateTimeField(verbose_name=_('created_at'), editable=False, default=timezone.now)

    class Meta:
        verbose_name = _('student')
        verbose_name_plural = _('students')

    def __str__(self):
        return '%s %s %s' % (self.first_name, self.name, self.last_name)

    def get_absolute_url(self):
        return "/students/%i/" % self.id


class StudentAddress(models.Model):
    student = models.ForeignKey(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING, verbose_name=_('country'), default=0)
    region = models.ForeignKey(Region, on_delete=models.DO_NOTHING, verbose_name=_('region'), default=0)
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING, verbose_name=_('district'), default=0)
    city = models.ForeignKey(City, on_delete=models.DO_NOTHING, verbose_name=_('city'), default=0)
    address = models.CharField(verbose_name=_('address'), max_length=300)
    permanent = models.BooleanField(verbose_name=_('permanent'), default=True)
    current = models.BooleanField(verbose_name=_('current'), default=True)

    class Meta:
        verbose_name = _('student_address')
        verbose_name_plural = _('students_addresses')

    def __str__(self):
        return '%s' % self.student


class StudentPassport(models.Model):
    student = models.ForeignKey(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    series = models.CharField(max_length=5, verbose_name=_('series'), default=0)
    number = models.PositiveIntegerField(verbose_name=_('number'), default=0)
    issue = models.DateField(verbose_name=_('valid to'), null=False, blank=False)
    organization = models.CharField(verbose_name=_('issued'), max_length=30, default=0)
    idn = models.CharField(verbose_name=_('INN'), max_length=14, default=0)

    class Meta:
        verbose_name = _('student_passport')
        verbose_name_plural = _('students_passports')

    def __str__(self):
        return '%s' % self.idn


class StudentBirthPlace(models.Model):
    student = models.OneToOneField(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING, verbose_name=_('country'), default=0)
    region = models.ForeignKey(Region, on_delete=models.DO_NOTHING, verbose_name=_('region'), default=0)
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING, verbose_name=_('district'), default=0)
    city = models.ForeignKey(City, on_delete=models.DO_NOTHING, verbose_name=_('city'), default=0)

    class Meta:
        verbose_name = _('student_birthplace')
        verbose_name_plural = _('students_birthplace')

    def __str__(self):
        return '%s' % self.country


class StudentAttestat(models.Model):
    student = models.ForeignKey(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    series = models.CharField(verbose_name=_('series'), max_length=4, default=0)
    number = models.PositiveIntegerField(verbose_name=_('number'), default=0)
    date = models.DateField(verbose_name=_('date'), null=False, blank=False, default=timezone.now)
    country = models.ForeignKey(Country, verbose_name=_('country'), on_delete=models.DO_NOTHING, default=0)
    region = models.ForeignKey(Region, verbose_name=_('region'), on_delete=models.DO_NOTHING, default=0)
    district = models.ForeignKey(District, verbose_name=_('district'), on_delete=models.DO_NOTHING, default=0)
    city = models.ForeignKey(City, verbose_name=_('city'), on_delete=models.DO_NOTHING, default=None)
    school = models.CharField(verbose_name=_('school'), max_length=255, default="№")

    class Meta:
        verbose_name = _('certificate from school')
        verbose_name_plural = _('certificates from school')

    def __str__(self):
        return '%s' % self.number


class StudentDiploma(models.Model):
    student = models.ForeignKey(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    series = models.CharField(verbose_name=_('series'), max_length=10, default=0)
    number = models.CharField(verbose_name=_('number'), max_length=50, default=0)
    university = models.CharField(verbose_name=_('university'), max_length=150, default=0)
    date = models.DateField(verbose_name=_('date'), null=False, default="2000-01-01")

    class Meta:
        verbose_name = _('available diploma')
        verbose_name_plural = _('available diplomas')

    def __str__(self):
        return '%s' % self.number


class Prikaz(models.Model):
    student = models.ForeignKey(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    number = models.CharField(verbose_name=_('number'), max_length=15, default=0)
    name = models.CharField(verbose_name=_('name'), max_length=150, default=0)
    date = models.DateField(verbose_name=_('date'), null=False, default="2005-01-01")

    class Meta:
        verbose_name = _('decree')
        verbose_name_plural = _('decrees')

    def __str__(self):
        return '%s' % self.number


class DiplomaFromUniversity(models.Model):
    student = models.ForeignKey(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    series = models.CharField(verbose_name=_('series'), max_length=10, default=0)
    number = models.CharField(verbose_name=_('number'), max_length=50, default=0)
    university = models.CharField(verbose_name=_('university'), max_length=150, default=0)
    date = models.DateField(verbose_name=_('date'), null=False, default="2000-01-01")

    class Meta:
        verbose_name = _('issued diploma')
        verbose_name_plural = _('issued diplomas')

    def __str__(self):
        return '%s' % self.number


class StudentAdditionalInf(models.Model):
    student = models.ForeignKey(Student, verbose_name=_('student'), on_delete=models.DO_NOTHING, default=0)
    note = models.TextField(verbose_name=_('note'), default="Нет")

    class Meta:
        verbose_name = _('additional information')
        verbose_name_plural = _('additional informations')

    def __str__(self):
        return '%s' % self.note


# Educational department tables
class UchPlanGroup(models.Model):
    group = models.ForeignKey(Groups, verbose_name=_('group'), on_delete=models.DO_NOTHING, default=0)
    semestr = models.PositiveIntegerField(verbose_name=_('semestr'), default=0)
    subject = models.ForeignKey(Subject, verbose_name=_('subject'), on_delete=models.DO_NOTHING, default=0)
    teacher = models.ForeignKey(Staff, verbose_name=_('teacher'), on_delete=models.DO_NOTHING, default=0)
    clock = models.FloatField(verbose_name=_('clock'), default=0.0)
    credit = models.FloatField(verbose_name=_('credit'), default=0.0)
    control = models.IntegerField(verbose_name=_('control_b'), choices=CONTROL_TYPE, default=EXAM, blank=False)
    edited = models.DateTimeField(verbose_name=_('edited'), default=timezone.now, editable=False)

    class Meta:
        verbose_name = _('uch_pl_group')
        verbose_name_plural = _('uch_pl_groups')

    def __str__(self):
        return '%s %s %s %s' % (self.group, self.semestr, self.subject, self.get_control_display())


class UchPlanStudents(models.Model):
    group_code = models.ForeignKey(Groups, verbose_name=_('group_code'), on_delete=models.DO_NOTHING, default=0)

apps/hr/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from apps.core.models import Department
from apps.catalogue.models import Position, AcademicStatus, AcademicDegree
from apps.catalogue.models import StaffStatus, Nationality, SEX_CHOISES, FEMALE
from apps.catalogue.models import Country, District, Region, City


WAITING = 0
PENDING = 1
FINISHED = 2
STATUS_CHOISES = (
    (WAITING, 'Waiting'),
    (PENDING, 'Pending'),
    (FINISHED, 'Finished'),
)


# Create your models here.
class Staff(models.Model):
    id = models.IntegerField(primary_key=True, auto_created=False, verbose_name=_('id'))
    last_name = models.CharField(max_length=100, verbose_name=_('first_name'))
    name = models.CharField(max_length=100, verbose_name=_('name'))
    middle_name = models.CharField(max_length=100, blank=True, verbose_name=_('last_name'))
    profile_img = models.FileField(upload_to='images/staff/',
                                   default='images/staff/profile.png',  verbose_name=_('profile_img'))
    birthdate = models.DateField(null=False, default="1980-01-01", verbose_name=_('birthday'))
    position = models.ForeignKey(Position, default=0, verbose_name=_('position'))
    academic_status = models.ForeignKey(AcademicStatus, default=0, verbose_name=_('academic_status'))
    academic_degree = models.ForeignKey(AcademicDegree, default=0, verbose_name=_('academic_degree'))
    staff_status = models.ForeignKey(StaffStatus, default=0,  verbose_name=_('staff_status'))
    academic_load = models.IntegerField(default=0, null=False, verbose_name=_('academic_load'))
    nationality = models.ForeignKey(Nationality, default=0, verbose_name=_('nationality'))
    mother_tongue = models.CharField(max_length=100, default="Русский", verbose_name=_('mother_tongue'))
    citizenship = models.ForeignKey(Country, default=0, verbose_name=_('citizenship'))
    sex = models.IntegerField(choices=SEX_CHOISES, default=FEMALE, verbose_name=_('sex'))
    email = models.EmailField(default='no@email.home', blank=True, verbose_name=_('email'))
    phone = models.CharField(max_length=15, blank=True, verbose_name=_('phone'))
    department = models.ForeignKey(Department, verbose_name=_('department'))
    quit = models.BooleanField(default=False, verbose_name=_('quit'))
    quit_date = models.DateField(default=timezone.now, verbose_name=_('quit_date'), null=True, blank=True)
    edited = models.DateTimeField(default=timezone.now, verbose_name=_('edited'), editable=False)

    class Meta:
        verbose_name = _('staff')
        verbose_name_plural = _('staff')

    def __str__(self):
        return '%s %s %s' % (self.last_name, self.name, self.middle_name)


class StaffAddress(models.Model):
    staff = models.ForeignKey(Staff, verbose_name=_('staff'))
    country = models.ForeignKey(Country, verbose_name=_('country'), default=0)
    region = models.ForeignKey(Region, verbose_name=_('region'), default=0)
    district = models.ForeignKey(District, verbose_name=_('district'), default=0)
    city = models.ForeignKey(City, verbose_name=_('city'), default=0)
    address = models.CharField(verbose_name=_('address'), max_length=300)
    permanent = models.BooleanField( verbose_name=_('permanent'), default=True)

    class Meta:
        verbose_name = _('staff_address')
        verbose_name_plural = _('staff_addresses')

    def __str__(self):
        return '%s' % self.address

templates/reports/group_vedomost.html
{% extends "base.html" %}
{% block content  %}
    <div>
        <div class="col-xs-3">
{#            {% if settings %}#}
{#                <h5 class="text-left"> {{ settings.shortname }}  </h5>#}
{#            {% endif %}#}
        </div>
    </div>
    <div>
        <div class="col-xs-6">
{#            <span><b>Программа:  </b>{{ group.department }}</span></br>#}
{#            <span><b>Направление:  </b>{{ group.name }}</span>#}
        </div>
        <div class="col-xs-6">
        </div>
    </div>
    <div class="white-background">

    </div>
{% endblock %}

templates/reports/marks_journal.html
{% extends "base.html" %}
{% block content  %}



{% endblock %}

templates/reports/student_card.html
{% extends "base.html" %}
{% block content  %}

    <div class="row">
        <h4 class="text-center">
            <strong>{{ settings.longname }}</strong>
        </h4>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <h6 class="text-left">Программа:</h6>
            <h6 class="text-left">Специальность/Направление:</h6>
            <h6 class="text-left">Группа:</h6>
        </div>
        <div class="col-xs-9">
            <h6 class="text-left"><strong>{{ student.group_code.department }}</strong></h6>
            <h6 class="text-left"><strong>{{ student.group_code.name }}</strong></h6>
            <h6 class="text-left"><strong>{{ student.group_code }}</strong></h6>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <h4 class="text-center">
                <b>Учебная карточка студента</b>
            </h4>
            <h5 class="text-center">
                <strong>{{ student.group_code.learningform }}</strong>
            </h5>
        </div>
        <div class="col-xs-3">
            <h5 class="text-right">
                <strong><u>ID студ. {{ student.id }}</u></strong>
            </h5>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <h6 class="text-left">Фамилия, Имя, Отчество:</h6>
            <h6 class="text-left">Дата рождения:</h6>
            <h6 class="text-left">Место рождения:</h6>
            <h6 class="text-left">Национальность:</h6>
            <h6 class="text-left">Социальное положение:</h6>
            <h6 class="text-left">Что окончила(а):</h6>
            <h6 class="text-left">Год окончания: </h6>
            <h6 class="text-left">Адрес местожительства</h6>
            <h6 class="text-left">Телефон:</h6>
            <h6 class="text-left">Зачислен(а) приказом в ВУЗ, </h6>
            <h6 class="text-left">На условиях:</h6>
        </div>
        <div class="col-xs-9">
            <h6 class="text-left">
                <strong>{{ student }}</strong>
            </h6>
            <h6 class="text-left">
                <strong>{{ student.birthday }}</strong>
            </h6>
            <h6 class="text-left">
            {% if birthplace %}
                {% for b in birthplace %}
                    <strong>{{ b.country }}, {{ b.region }}</strong>
                {% endfor %}
            {% else %}
                <strong>Данные не указаны</strong>
            {% endif %}
            </h6>
            <h6 class="text-left">
                <strong>{{ student.nationality }}</strong>
            </h6>
            <h6 class="text-left">
                <strong>{{ student.get_maritial_status_display }}</strong>
            </h6>
            <h6 class="text-left">
                {% if attestat %}
                    {% for att in attestat %}
                        {% if att.region.name == att.city.name %}
                            <strong>
                                {{ att.school }}
                                {{ att.district.name }},
                                {{ att.city.name }},
                                {{ att.country.name }}
                            </strong>
                        {% else %}
                            <strong>
                                {{ att.school }}
                                {{ att.city.name }},
                                {{ att.district.name }},
                                {{ att.region.name }},
                                {{ att.country.name }}
                            </strong>
                        {% endif %}
                    {% endfor %}
                {% elif diploma%}
                    {% for dip in diploma %}
                        <strong>
                            {{ dip.university }}
                        </strong>
                    {% endfor %}
                {% endif %}
            </h6>
            <h6 class="text-left">
                {% if attestat %}
                    {% for att in attestat %}
                        <strong>
                            {{ att.date }}
                        </strong>
                    {% endfor %}
                {% elif diploma%}
                    {% for dip in diploma %}
                        <strong>
                            {{ dip.date }}
                    {% endfor %}
                {% endif %}
            </h6>
            <h6 class="text-left">
            {% if address %}
                {% for adrs in address %}
                    <strong>
                        {{ adrs.address }},
                        {% if adrs.region.name == adrs.city.name %}
                            {{ adrs.district.name }},
                            {{ adrs.city.name }},
                        {% else %}
                            {{ adrs.city.name }},
                            {{ adrs.district.name }},
                            {{ adrs.region.name }},
                        {% endif %}
                        {{ adrs.country.name }}
                    </strong>
                {% endfor %}
            {% else %}
                Нет текущего адреса
            {% endif %}
            </h6>
            <h6 class="text-left">
                <strong>{{ student.phone }}</strong>
            </h6>
            <h6 class="text-left">
                {% for pr in prikaz %}
                    {% if forloop.first %}
                        <strong>приказ {{ pr.number }} от {{ pr.date }}{{ pr.enrollment.name }}</strong>
                    {% endif %}
                {% endfor %}
            </h6>
            <h6 class="text-left">
                <strong>{{ student.enrollment }}</strong>
            </h6>
        </div>
    </div>
    <div class="table-print-body row">
        <h6 class="text-center">
            <strong>
                Поощрения, взыскания, перерывы в академичиской учебе, переводы с курса на курс:
            </strong>
        </h6>
        <table width="100%">
            <thead>
                <tr>
                    <th width="10%">Курс</th>
                    <th width="45%">№ и дата приказа</th>
                    <th width="45%"> Содержание приказа</th>
                </tr>
            </thead>
            <tbody>
            {% for pri in prikaz %}
                <tr>
                    <td align="center" valign="middle"></td>
                    <td align="center" valign="middle">{{ pri.number }} от {{ pri.date }}</td>
                    <td align="center" valign="middle">{{ pri.name }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle">&nbsp;</td>
            </tr>
            <tr>
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle">&nbsp;</td>
            </tr>
            <tr>
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle">&nbsp;</td>
                <td align="center" valign="middle">&nbsp;</td>
            </tr>

            </tbody>
        </table>
    </div>
    <br>

{% endblock %}

templates/reports/students_list_in_group.html
{% extends "base.html" %}
{% block content  %}

    <div class="row">
        <div class="col-xs-3">
            {% if settings %}
                <h5 class="text-left"><strong>{{ settings.longname }}</strong></h5>
            {% endif %}
        </div>
        <div class="col-xs-6">
            <h4 class="text-center">
                {% if group %}
                    <strong>
                        Список группы - {{ group.code }}
                    </strong>
                {% endif  %}
            </h4>
        </div>
        <div class="col-xs-3">
            <h5 class="text-right"> {% now "d.m.Y" %}  </h5>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-xs-12">
            <h5 class="text-left"><b>Программа:  </b>{{ group.department }}</h5>
            <h5 class="text-left"><b>Направление:  </b>{{ group.name }}</h5>
        </div>
    </div>
    <br>
    <div class="row table-print-body">
        <table width="100%">
            <thead>
                <tr>
                    <th style="width:10%">ID</th>
                    <th style="width:50%">Фамилия Имя Отчество</th>
                    <th style="width:15%">Дата рожд.</th>
                    <th style="width:12%">Пол</th>
                    <th style="width:20%">Примечания</th>
                </tr>
            </thead>
            <tbody>
                {% for student in student_list%}
                    <tr>
                        <td align="center" valign="middle">{{ student.id }}</td>
                        <td valign="middle">{{ student.first_name }} {{ student.name}} {{ student.last_name }}</td>
                        <td align="center" valign="middle">{{ student.birthday | date:"d-m-Y" }}</td>
                        <td align="center" valign="middle">{{ student.get_sex_display }}</td>
                        <td></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}