urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework_swagger.views import get_swagger_view

from apps.home.views import IndexView
from apps.cv.views import GenerateCV, CvStaffIndex
from apps.core.views import DepartmentsIndex, GroupsIndex
from apps.edudep.views import (StudentsIndex, StudentDetailViewSet,
                               UchPlanGroupIndex, UchPlanStudentIndex,
                               UchPlanGroupDetailView, StudentCreateViewSet)
from apps.indplans.views import EducationalWork
from apps.abiturient.views import AbiturientsIndex, AbiturientView, AbiturientsIndexList
from apps.reports.views import StudentSpravkaView, StudentsMovementsJournalView
from apps.reports.views import (StudentsListInGroupView, UchPlanGroupCurrentDetailPDFView,
                                UchPlanStudentsBegunok, UchPlanStudentsCurrSemestr,
                                UchPlanStudentsSemestr, UchPlanGroupDetailPDFView,
                                StudentCardView, JournalOfMarks, StudentByDepartments,
                                StudentByNationality)


admin.site.site_header = 'BDOC Web'
schema_view = get_swagger_view(title='BDOC API')

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^docs/api/', schema_view),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('apps.core.urls', namespace='core')),
    url(r'^auth/', include('apps.auth.urls', namespace='auth')),
    url(r'^cv/staff/$', CvStaffIndex.as_view(), name='cv_list'),
    url(r'^cv/staff/(?P<pk>\d+)/$', GenerateCV.as_view(), name='cv_id'),
    url(r'^departments/$', DepartmentsIndex.as_view(), name='departments_list'),
    url(r'^groups/$', GroupsIndex.as_view(), name='groups_list'),
    url(r'^students/$', StudentsIndex.as_view(), name='students_list'),
    url(r'^uchplans/groups/$', UchPlanGroupIndex.as_view(), name='uchplgroup_list'),
    url(r'^uchplans/groups/(?P<pk>\d+)/$', UchPlanGroupDetailView.as_view(), name='uchplgroup_detail'),
    url(r'^uchplans/students/$', UchPlanStudentIndex.as_view(), name='uchplstudent_list'),
    url(r'^uchplans/students/(?P<pk>\d+)/b/print/$', UchPlanStudentsBegunok.as_view(), name='uchplstudent_begunok'),
    url(r'^indplan/eduwork/$', EducationalWork.as_view(), name='eduwork_list'),
    url(r'^indplan/eduwork/(?P<pk>\d+)/$', EducationalWork.as_view(), name='eduwork_id'),
    url(r'^abitur/inner$', AbiturientsIndex.as_view(), name='abitur_inner_list'),
    url(r'^abitur/$', AbiturientsIndexList.as_view(), name='abitur_list'),
    url(r'^abitur/inner/(?P<pk>\d+)/$', AbiturientView.as_view(), name='abitur_inner_id'),
    url(r'^reports/student/(?P<pk>\d+)/spravka/$', StudentSpravkaView.as_view(), name='student_spravka'),
    url(r'^reports/group/(?P<pk>\d+)/journal_students/$', StudentsMovementsJournalView.as_view(), name='students_movements'),
    url(r'^reports/group/(?P<pk>\d+)/studentsingr/$', StudentsListInGroupView.as_view(), name='students_movements'),
    url(r'^reports/group/(?P<pk>\d+)/current_v/print/$', UchPlanGroupCurrentDetailPDFView.as_view(), name='current_vedomost_print'),
    url(r'^reports/group/(?P<pk>\d+)/v/print/$', UchPlanGroupDetailPDFView.as_view(), name='vedomost_print'),
    url(r'^reports/group/(?P<pk>\d+)/journal/download/$', JournalOfMarks.as_view(), name='journal_download'),
    url(r'^reports/student/(?P<pk>\d+)/curr_uchplan/$', UchPlanStudentsCurrSemestr.as_view(), name='curruchplan_print'),
    url(r'^reports/student/(?P<pk>\d+)/curr_uchplan/(?P<sem>\d+)/$', UchPlanStudentsSemestr.as_view(), name='semuchplan_print'),
    url(r'^reports/student/(?P<pk>\d+)/studentcard/$', StudentCardView.as_view(), name='student_card_print'),
    url(r'^reports/bydepartment/$', StudentByDepartments.as_view(), name='student_by_department'),
    url(r'^reports/bynationality/$', StudentByNationality.as_view(), name='student_by_nationality'),
    url(r'^student/new/$', StudentCreateViewSet.as_view(), name='student_create'),
    url(r'^student/(?P<pk>\d+)/$', StudentDetailViewSet.as_view(), name='student_detail'),
    url(r'^api/docs/', include('rest_framework_docs.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/abiturient/models.py
from django.db import models
from apps.core.models import Department
from apps.catalogue.models import LearningForm, ORT_CERT_COLOR, DEFAULT_COLOR
from django.utils.translation import ugettext_lazy as _


EXAM = 0
TEST_WR = 1
TEST_ONLINE = 2
INTERVIEW = 3
EXAM_TYPE = (
    (EXAM, 'Экзамен письменный'),
    (TEST_WR, 'Тест письменный'),
    (TEST_ONLINE, 'Тест онлайн'),
    (INTERVIEW, 'Собеседование'),
)


# Create your models here.
class Abiturient(models.Model):
    id = models.AutoField(db_column="id", verbose_name=_('id'), primary_key=True)
    regnumber = models.CharField(db_column="regnumber", verbose_name=_('regnumer'), max_length=255, null=False, blank=False)
    lastname = models.CharField(db_column="lastname", verbose_name=_('first_name'), max_length=255, null=False, blank=False)
    name = models.CharField(db_column="name", verbose_name=_('name'), max_length=255, null=False, blank=True)
    middlename = models.CharField(db_column="middlename", verbose_name=_('last_name'), max_length=255, null=True, blank=True)
    point = models.PositiveIntegerField(db_column="point", verbose_name=_('ball'), default=0)
    tour = models.PositiveIntegerField(db_column="tour", verbose_name=_('tour'), default=1)
    department = models.ForeignKey(Department, db_column="department", verbose_name=_('department'), on_delete=models.SET_NULL, null=True)
    learningform = models.ForeignKey(LearningForm, db_column="leaningform", verbose_name=_('learning_form'), on_delete=models.SET_NULL, null=True)
    phone = models.IntegerField(db_column="phone", verbose_name=_('phone'), null=True, blank=True)
    exam = models.BooleanField(db_column="exam", verbose_name=_('exam'), default=False)
    year = models.DateField(db_column="year", verbose_name=_('year'), null=False)

    class Meta:
        db_table = "abiturient"
        verbose_name = _('abiturient')
        verbose_name_plural = _('abiturients')
        get_latest_by = "id"
        ordering=["-regnumber", "-year"]

    def __str__(self):
        return "%s" % self.regnumber


class AbitOrt(models.Model):
    id = models.AutoField(db_column="id", verbose_name=_('id'), primary_key=True)
    abiturient = models.OneToOneField(Abiturient, db_column="abiturient", verbose_name=_('abiturient'), on_delete=models.SET_NULL, null=True)
    code = models.IntegerField(db_column="code", verbose_name=_('cert_code'), default=0, null=False, blank=False)
    color = models.CharField(db_column="color", verbose_name=_('colour'), max_length=10, choices=ORT_CERT_COLOR, default=DEFAULT_COLOR)
    main_test = models.PositiveIntegerField(db_column="main_test", verbose_name=_('main_test'), default=0, null=False, blank=False)
    english = models.PositiveIntegerField(db_column="english", verbose_name=_('english_language'), default=0)
    math = models.PositiveIntegerField(db_column="math", verbose_name=_('math'), default=0)
    history = models.PositiveIntegerField(db_column="history", verbose_name=_('history'), default=0)
    physics = models.PositiveIntegerField(db_column="physics", verbose_name=_('physics'), default=0)
    biology = models.PositiveIntegerField(db_column="biology", verbose_name=_('biology'), default=0)
    chemistry = models.PositiveIntegerField(db_column="chemistry", verbose_name=_('chemistry'), default=0)
    year = models.DateField(db_column="year", verbose_name=_('year'), auto_now_add=True)
    
    class Meta:
        db_table = "abiturort"
        verbose_name = _('abitur_cert')
        verbose_name_plural = _('abitur_certs')
        get_latest_by = "id"
        ordering = ["-id"]

    def get_summ_of_points(self, sum_of_point=0):
        point_agg = AbitOrt.objects.annotate(
            summ_point=models.F('main_test') 
                + models.F('english')+ models.F('math')
                + models.F('history')+ models.F('physics')
                + models.F('biology')+ models.F('chemistry'))
        return sum_of_point

    def __str__(self):
        return "%s" % self.abiturient


class AbitSubject(models.Model):
    id = models.AutoField(db_column="id", verbose_name=_('id'), primary_key=True)
    name = models.CharField(db_column="name", verbose_name=_('name_of_smth'), max_length=255)

    class Meta:
        db_table = "abit_subject"
        verbose_name = _('enrollment_exam')
        verbose_name_plural = _('enrollment_exams')
        ordering = ["-name"]

    def __str__(self):
        return "%s" % self.name


class Exams(models.Model):
    id = models.AutoField(db_column="id", verbose_name=_('id'), primary_key=True)
    abiturient = models.ForeignKey(Abiturient, db_column="abiturient_id", verbose_name=_('abiturient'),
                                   on_delete=models.SET_NULL, null=True, blank=True)
    subject = models.ForeignKey(AbitSubject, db_column="subject_id", verbose_name=_('subject'),
                                on_delete=models.SET_NULL, null=True, blank=True)
    exam_type = models.IntegerField(db_column="exam_type", verbose_name=_('type_of_control'),
                                    choices=EXAM_TYPE, default=INTERVIEW)
    date = models.DateField(db_column="date", verbose_name=_('date'), auto_now_add=True)
    point = models.FloatField(db_column="point", verbose_name=_('ball'), default=0)
    teacher = models.CharField(db_column="teacher", verbose_name=_('teacher'), max_length=300, blank=True)

    class Meta:
        db_table = "abiturexam"
        verbose_name = _('exam_of_abitur')
        verbose_name_plural = _('abitur_exams')
        ordering = ['-date']

    def __str__(self):
        return "%s" % self.subject

apps/abiturient/views.py
from rest_framework import generics
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
import time
from .models import Abiturient, Exams
from .serailizers import AbiturientSerializer


# Create your views here.
class AbiturientsIndexList(LoginRequiredMixin, ListView):
    template_name = "abiturient/abiturient_list.html"
    model = Abiturient
    paginate_by = 20
    queryset = Abiturient.objects.filter(exam=False, year__year=time.strftime("%Y"))
    context_object_name = "abiturient_list"


class AbiturientsIndex(LoginRequiredMixin, ListView):
    template_name = "abiturient/abiturient_inner_list.html"
    model = Abiturient
    paginate_by = 20
    queryset = Abiturient.objects.filter(exam=True, year__year=time.strftime("%Y"))
    context_object_name = "abiturient_list"


class AbiturientView(LoginRequiredMixin, DetailView):
    login_url = '/admin/login/'
    template_name = 'abiturient/abiturient_inner.html'
    queryset = Abiturient.objects.filter(exam=True).select_related()
    context_object_name = 'abiturient'

    def get_context_data(self, **kwargs):
        context = super(AbiturientView, self).get_context_data(**kwargs)
        try:
            context["exam_list"] = Exams.objects.select_related().filter(abiturient=self.object)
        except Exams.DoesNotExist:
            context["exam_list"] = []
        return context


class AbiturientAPIView(generics.ListCreateAPIView):
    """
    List all abiturients, or create a new snippet.
    """
    queryset = Abiturient.objects.filter(exam=False, year__year=time.strftime("%Y"))
    serializer_class = AbiturientSerializer


class AbiturientDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, update or delete a abiturient instance.
    """
    queryset = Abiturient.objects.all()
    serializer_class = AbiturientSerializer

apps/cv/views.py
from rest_framework import viewsets
from .serializers import StaffCvSerializer, StaffSerializer

from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.hr.models import Staff, StaffAddress
from apps.cv.models import AdditionalInf, Work, Conferences
from apps.cv.models import Education, Publications, Seminars
from apps.cv.models import LanguageKnowledge, Projects


class StaffCvViewSet(viewsets.ModelViewSet):
    queryset = Staff.objects.all()
    serializer_class = StaffCvSerializer


class StaffListViewSet(viewsets.ModelViewSet):
    queryset = Staff.objects.all()
    serializer_class = StaffSerializer


class CvStaffIndex(LoginRequiredMixin, ListView):
    template_name = "cv/cv_staff_list.html"
    model = Staff
    paginate_by = 12
    queryset = Staff.objects.all()
    context_object_name = "staff_list"


class GenerateCV(LoginRequiredMixin, DetailView):
    login_url = '/admin/login/'
    template_name = 'cv/cv_staff.html'
    queryset = Staff.objects.select_related()
    context_object_name = 'cv'

    def get_context_data(self, **kwargs):
        context = super(GenerateCV, self).get_context_data(**kwargs)
        try:
            context["address_list"] = StaffAddress.objects.select_related().get(staff=self.object, permanent=True)
        except StaffAddress.DoesNotExist:
            context["address_list"] = []
        context["conferences_list"] = Conferences.objects.filter(staff=self.object)
        context["education_list"] = Education.objects.filter(staff=self.object)
        context["work_list"] = Work.objects.filter(staff=self.object)
        context["addition_list"] = AdditionalInf.objects.filter(staff=self.object)
        context["publications_list"] = Publications.objects.filter(staff=self.object)
        context["seminars_list"] = Seminars.objects.filter(staff=self.object)
        context["langknowledge_list"] = LanguageKnowledge.objects.filter(staff=self.object)
        context["projects_list"] = Projects.objects.filter(staff=self.object)
        return context

templates/abiturient/abiturient_inner.html
{%  extends "base.html" %}
{% block content %}
	<div>
		<div class="col-xs-6">
			<ol>
				<li>Экзаменационный лист служит пропуском на экзамне</li>
				<li>По окончании вступительных экзаменов экзаменационный лист должен быть возвращен в приемную комиссию.</li>
				<li>При получении неудовлетворительной оценки экзаменационный лист остается у экзаменатора</li>
				<li>Не зачисленные в учебное заведение получат обратно свои документы в приемной комиссии после сдачи экзаменационного листа</li>
				<li>Опоздавшие и не явившиеся в срок допускаются с разрешения ответственного секретаря приемной комиссии</li>
			</ol>
		</div>
		<div class="col-xs-6">
			<div class="">
				<div class="col-xs-6">
					<img alt="Abiturient Image" />
				</div>
				<div class="col-xs-6">
					<h6 class="right"><u>Форма №4</u></h6>
					<h5 class="center">Университет Адам</h5>
					<h6 class="right">{{abiturient.learningform}}</h6>
				</div>
			</div>
			<h4><b> Экзаменационный лист № {{ abiturient.regnumber }} </b></h4>
                        <ul>
                           <li>Специальность: {{ abiturient.department }}</li>
                           <li>Фамилия:       {{ abiturient.lastname }}</li>
                           <li>Имя:           {{ abiturient.name }}</li>
                           <li>Отчество:      {{ abiturient.middlename }}</li>
                        </ul>
                        <p>Дата выдачи:"___"__________{% now "Y" %}</p>
                        <p>Ответственный секретарь приемной комиссии _________</p>
		</div>
	</div>
</div>

<div class="content-second">
	<div>
		<div class="col-xs-12">
			<h4><b>I. Оценки, полученные на вступительных экзаменах </b></h4>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>№</th>
						<th>Наименование дисциплины</th>
						<th>Характер экзамена</th>
						<th>Дата</th>
						<th>Оценка(баллы)</th>
						<th>ФИО экзаменатора</th>
						<th>Подпись экзаменатора</th>
					</tr>
				</thead>
				<tbody>
                    {%if exam_list %}
                        {% for exam in exam_list %}
                            <tr>
                                <td> {{ forloop.counter }} </td>
                                <td> {{ exam.subject}} </td>
                                <td> {{ exam.get_exam_type_display}} </td>
                                <td>  </td>
                                <td> {{ exam.point}} </td>
                                <td> {{ exam.teacher }} </td>
                                <td>  </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
				</tbody>
			</table>
            <h6><b>II. Сумма баллов, полученных на вступительных экзаменах _____ </b></h6>
            <p class="right">Ответственный секретарь приемной комиссии ___________(Подпись)</p>
		</div>
    </div>
    </div>
    <div>

{% endblock %}

templates/abiturient/abiturient_inner_list.html
{% extends "base.html" %}
{% block content %}
<div class="grid simple ">
    <div class="grid-title">
        <h4>
            <span class="semi-bold">Список абитуриентов(Внутренние)</span>
        </h4>
    </div>
    <div class="grid-body " style="overflow: hidden; display: block;">
        <table id="datatable" class="table table-hover table-condensed">
            <thead>
                <tr role="row">
                    <th style="width:10%">№</th>
                    <th style="width:10%">ID</th>
                    <th style="width:20%">Фамилия</th>
                    <th style="width:20%">Имя</th>
                    <th style="width:20%">отчество</th>
                </tr>
            </thead>
            <tbody>
                {% for abiturient in abiturient_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="/abitur/inner/{{abiturient.id}}">{{ abiturient.regnumber }}</a></td>
                        <td>{{ abiturient.lastname }}</td>
                        <td>{{ abiturient.name }}</td>
                        <td>{{ abiturient.middlename }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "partials/pagination.html" %}
    </div>
</div>
    <script type="text/javascript">
{#        var myData = [];#}
{#        {% for item in items %}#}
{#                myData.push([#}
{#                    '{{ item.date|date:"Y-m-d H:m" }}',#}
{#                    '{{ item.value }}'#}
{#                ]);#}
{#        {% endfor %}#}
{#        var myTable = $('#datatable').DataTable({#}
{#            order: [[0, "asc"]],#}
{#            pageLength: 25,#}
{#            responsive: true,#}
{#            columns: [#}
{#                {sTitle: "Date", sWidth: "100px"},#}
{#                {sTitle: "value", sWidth: "50px"}#}
{#            ],#}
{#            data: myData#}
{#        });#}
{#    $(document).ready(function() {#}
{#    $('#datatable').DataTable( {#}
{#        "processing": true,#}
{#        "serverSide": true,#}
{#        "ajax": {#}
{#            "url": "/api/abiturinets/?format=json",#}
{#            "dataType": "jsonp"#}
{#        }#}
{#    } );#}
{#} );#}
    </script>
{% endblock %}

templates/abiturient/abiturient_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static "assets/plugins/DataTables/DataTables-1.10.16/css/jquery.dataTables.css" %}"/>
{% endblock %}
{% block content %}
<div class="row-fluid">
    <div class="span-12">
        <div class="grid simple">
            <div class="grid-title">
                <h4>
                    <span class="semi-bold">Список абитуриентов</span>
                </h4>
            </div>
            <div class="grid-body" style="overflow: hidden; display: block;">
                <table id="abiturient" class="table responsive table-striped dataTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Рег. номер</th>
                            <th>Фамилия</th>
                            <th>Имя</th>
                            <th>Отчество</th>
                            <th>Балл</th>
                            <th>Тур</th>
                            <th>Экзамен</th>
                            <th>Год</th>
                            <th>Департамен</th>
                            <th>Форма обучения</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

</script>
{% endblock %}
{% block scripts %}
{{ block.super }}
<script type="text/javascript" src="{% static "assets/plugins/DataTables/DataTables-1.10.16/js/jquery.dataTables.js" %}"></script>
<script type="text/javascript" src="{% static "assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js" %}"></script>
<script type="text/javascript" src="{% static "assets/plugins/jquery-block-ui/jqueryblockui.js"%}"></script>
<script type="text/javascript" src="{% static "assets/plugins/jquery-numberAnimate/jquery.animateNumbers.js"%}"></script>
<script type="text/javascript" src="{% static "assets/plugins/bootstrap-select2/select2.min.js"%}"></script>
<script type="text/javascript" src="{% static "assets/plugins/jquery-datatable/js/jquery.dataTables.min.js"%}"></script>
<script type="text/javascript" src="{% static "assets/plugins/jquery-datatable/extra/js/dataTables.tableTools.min.js"%}"></script>
<script type="text/javascript" src="{% static "assets/plugins/datatables-responsive/js/datatables.responsive.js"%}"></script>
<script type="text/javascript" src="{% static "assets/plugins/datatables-responsive/js/lodash.min.js"%}"></script>

<script>
$('#abiturient').dataTable({
    responsive: true,
    select: true,
    buttons: [
        'pdf',
    ],
    ajax: {
        url: '/api/abiturinets/?format=json',
        dataSrc: ''
    },
    aoColumns: [
        { "data": "id"},
        { "data": "regnumber"},
        { "data": "lastname"},
        { "data": "name"},
        { "data": "middlename"},
        { "data": "point"},
        { "data": "tour"},
        {
            "mData": function (data, type, dataToSet) {
                if(data.exam){
                    return "<i class='fa fa-plus-square-o'></i>";
                }else{
                    return "<i class='fa fa-minus-square-o'></i>";
                }

            }
        },
        { "data": "year"},
        { "data": "department"},
        { "data": "learningform"},
{#        {#}
{#            data: null,#}
{#            className: "center",#}
{#            defaultContent: 'your html code'#}
{#        }#}
    ],
    "columnDefs": [
        {
            "className": "dt-center", "targets": "_all"
        }
      ],
    language :{
        "url": "{% static "assets/plugins/DataTables/DataTables-1.10.16/lang/russian.json" %}"
    }
});
</script>
{% endblock %}